# Generated by Django 3.2.8 on 2021-11-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='source',
            field=models.URLField(default='https://willowthe.dev'),
        ),
    ]
