# Generated by Django 3.2.8 on 2021-11-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_home', '0003_header'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('placement',)},
        ),
        migrations.AddField(
            model_name='card',
            name='placement',
            field=models.IntegerField(default=0),
        ),
    ]
